receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Convert cumulative metrics to delta for Dynatrace
  cumulativetodelta:
    max_stale: 10m
  
  # Batch processor for performance
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  
  # Resource processor to add metadata
  resource:
    attributes:
      - key: deployment.environment
        value: "cloud-run"
        action: upsert
      - key: service.instance.id
        from_attribute: faas.instance
        action: insert
      - key: cloud.provider
        value: "gcp"
        action: upsert
      - key: cloud.platform
        value: "gcp_cloud_run"
        action: upsert

  # Memory limiter to prevent OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 256

exporters:
  # Export to Dynatrace
  otlphttp:
    endpoint: "https://${DT_TENANT}.live.dynatrace.com/api/v2/otlp"
    headers:
      Authorization: "Api-Token ${DT_API_TOKEN}"
  
  # Debug exporter for troubleshooting
  debug:
    verbosity: basic
    sampling_initial: 2
    sampling_thereafter: 500

  # Logging exporter for local testing
  logging:
    verbosity: basic

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp, logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, cumulativetodelta, resource, batch]
      exporters: [otlphttp, logging]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp, logging]

  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888
