version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_RESOURCE_ATTRIBUTES=service.name=dynatrace-test-app,service.version=1.0.0,deployment.environment=local
      - OTEL_SERVICE_NAME=dynatrace-test-app
      - OTEL_LOG_LEVEL=info
      - PORT=8080
    depends_on:
      collector:
        condition: service_healthy

  collector:
    build: ./collector
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "13133:13133" # Health check
      - "8888:8888"   # Prometheus metrics
    environment:
      - DT_TENANT=${DT_TENANT}
      - DT_API_TOKEN=${DT_API_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
