receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 100
    send_batch_max_size: 512

  resource:
    attributes:
      - key: collector.name
        value: "local-file-collector"
        action: insert

exporters:
  # Console exporter - prints to collector logs
  debug:
    verbosity: normal
    sampling_initial: 10
    sampling_thereafter: 100

  # File exporters - save all data to files in user home directory
  file/traces:
    path: /home/otelcol/telemetry/traces.jsonl
    format: json

  file/metrics:
    path: /home/otelcol/telemetry/metrics.jsonl
    format: json

  file/logs:
    path: /home/otelcol/telemetry/logs.jsonl
    format: json

  # Combined file for all telemetry
  file/all:
    path: /home/otelcol/telemetry/all-telemetry.jsonl
    format: json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug, file/traces, file/all]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug, file/metrics, file/all]

    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug, file/logs, file/all]

  extensions: [health_check]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133